### ISSUE TITLE
binning in physical distance

### ISSUE THREAD

**Issue by aurelepiazza** [koszullab/hicstuff#12]
There is an issue with binning using physical distance (as run on ubuntu in windows):
Here is the error I am getting when I run the view function:

hicstuff view -b 5kb -o AP11_matrix_5kb abs_fragments_contacts_weighted.txt
Traceback (most recent call last):
  File "/mnt/d/Science/Experiments/HiC/src/hicstuff/hicstuff/commands.py", line 184, in execute
    binning = int(bin_str)
ValueError: invalid literal for int() with base 10: '5KB'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/hicstuff", line 11, in <module>
    load_entry_point('hicstuff', 'console_scripts', 'hicstuff')()
  File "/mnt/d/Science/Experiments/HiC/src/hicstuff/hicstuff/main.py", line 51, in main
    command.execute()
  File "/mnt/d/Science/Experiments/HiC/src/hicstuff/hicstuff/commands.py", line 188, in execute
    unit_pos = re.match(r"[KM]?B[P]?$", bin_str).start()
AttributeError: 'NoneType' object has no attribute 'start'

**Comment by cmdoret** [comment]
Thanks for the report ! Fixed this in a1691892e5bb26d60f6f3d006b7f34a1a44d2ac5 and added it in version 0.1.13. 
Don't forget to `pip install --upgrade hicstuff` :)
