### ISSUE TITLE
Error with Docker image

### ISSUE THREAD

**Issue by AllanSSX** [koszullab/hicstuff#47]
Hi,

I've tried to run Hicstuff using Docker but it's seems a least 1 dependency is broken.

```bash
INFO :: ## hicstuff: v3.0.0 log file
INFO :: ## date: 2021-04-26 12:20:04
INFO :: ## enzyme: DpnII
INFO :: ## input1: 0-data/SRR10801760_1.fastq.gz
INFO :: ## input2: 0-data/SRR10801760_2.fastq.gz
INFO :: ## ref: 0-data/GCA_011032805.1.fna
INFO :: ---
INFO :: bowtie2 index not found at hicstuff/tmp/genome.fasta, generating a local temporary index.
INFO :: 115487109 reads to parse
INFO :: Truncating unaligned reads to 20bp and mapping.
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
[E::hts_open_format] Failed to open file "hicstuff/tmp/8ecddecf/temp_alignment.bam" : No such file or directory
Traceback (most recent call last):
  File "/opt/conda/bin/hicstuff", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/hicstuff/main.py", line 56, in main
    command.execute()
  File "/opt/conda/lib/python3.7/site-packages/hicstuff/commands.py", line 878, in execute
    tmp_dir=self.args["--tmpdir"],
  File "/opt/conda/lib/python3.7/site-packages/hicstuff/pipeline.py", line 804, in full_pipeline
    read_len=read_len,
  File "/opt/conda/lib/python3.7/site-packages/hicstuff/pipeline.py", line 87, in align_reads
    read_len=read_len,
  File "/opt/conda/lib/python3.7/site-packages/hicstuff/iteralign.py", line 178, in iterative_align
    remaining_reads = filter_bamfile(temp_alignment, iter_out[-1], min_qual)
  File "/opt/conda/lib/python3.7/site-packages/hicstuff/iteralign.py", line 305, in filter_bamfile
    temp_bam = ps.AlignmentFile(temp_alignment, "rb", check_sq=False)
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 941, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file `hicstuff/tmp/8ecddecf/temp_alignment.bam`: No such file or directory
```

Any idea ?

**Comment by cmdoret** [comment]
Hi @AllanSSX,

It seems this was caused by a compatibility problem between samtools and libcrypto. I have updated the dockerfile and made a new release (v3.0.1). The problem should be fixed now, does it work for you ?

Cyril

**Comment by AllanSSX** [comment]
Yes, it works well.

Thank you!
