### ISSUE TITLE
Cutsite error

### ISSUE THREAD

**Issue by sarah872** [koszullab/hicstuff#50]
Hi,
when running hicstuff with the cutsite mapper, I get the following error:

```
INFO :: ## hicstuff: v3.0.2 log file
INFO :: ## date: 2021-07-23 21:10:07
INFO :: ## enzyme: HhaI
INFO :: ## input1: /tmp/slurm-1792689/for.fq
INFO :: ## input2: /tmp/slurm-1792689/rev.fq
INFO :: ## ref: genome.fasta
INFO :: ---
INFO :: bowtie2 index not found at bowtie2.HhaI.cutsite.filter.duplicates/tmp/genome.fasta, generating a local temporary index.
INFO :: Number of pairs before digestion: 15686055
INFO :: Number of pairs after digestion: 779207729
Traceback (most recent call last):
  File "/home/bin/hicstuff", line 8, in <module>
    sys.exit(main())
  File "/home/lib/python3.7/site-packages/hicstuff/main.py", line 56, in main
    command.execute()
  File "/home/lib/python3.7/site-packages/hicstuff/commands.py", line 881, in execute
    tmp_dir=self.args["--tmpdir"],
  File "/home/lib/python3.7/site-packages/hicstuff/pipeline.py", line 802, in full_pipeline
    iterative=iterative,
UnboundLocalError: local variable 'iterative' referenced before assignment
Traceback (most recent call last):
  File "/home/bin/hicstuff", line 8, in <module>
    sys.exit(main())
  File "/home/lib/python3.7/site-packages/hicstuff/main.py", line 56, in main
    command.execute()
  File "/home/lib/python3.7/site-packages/hicstuff/commands.py", line 844, in execute
    "You cannot filter without specifying a restriction enzyme."
ValueError: You cannot filter without specifying a restriction enzyme.
Traceback (most recent call last):
  File "/home/bin/hicstuff", line 8, in <module>
    sys.exit(main())
  File "/home/lib/python3.7/site-packages/hicstuff/main.py", line 56, in main
    command.execute()
  File "/home/lib/python3.7/site-packages/hicstuff/commands.py", line 844, in execute
    "You cannot filter without specifying a restriction enzyme."
ValueError: You cannot filter without specifying a restriction enzyme.
Traceback (most recent call last):
  File "/home/bin/hicstuff", line 8, in <module>
    sys.exit(main())
  File "/home/lib/python3.7/site-packages/hicstuff/main.py", line 56, in main
    command.execute()
  File "/home/lib/python3.7/site-packages/hicstuff/commands.py", line 844, in execute
    "You cannot filter without specifying a restriction enzyme."
ValueError: You cannot filter without specifying a restriction enzyme.
```

However, an enzyme is specified...

**Comment by ABignaud** [comment]
Hi Sarah, 

Thank you for using our code. It was a bug in the cutsite command. I made a commit to correct it and we will soon make a release with the correction.

Amaury

**Comment by sarah872** [comment]
thank you! it's running now without error
