### ISSUE TITLE
Issue with the view function

### ISSUE THREAD

**Issue by aurelepiazza** [koszullab/hicstuff#52]
Hi guys! I ran into an issue using the latest version of hicstuff (3.0.3) while trying to render matrices with the view function. Here is the error:
Traceback (most recent call last):
  File "/home/apiazza/.local/bin/hicstuff", line 8, in <module>
    sys.exit(main())
  File "/home/apiazza/.local/lib/python3.8/site-packages/hicstuff/main.py", line 56, in main
    command.execute()
  File "/home/apiazza/.local/lib/python3.8/site-packages/hicstuff/commands.py", line 714, in execute
    current_cmap = cm.get_cmap().copy()
AttributeError: 'ListedColormap' object has no attribute 'copy'

Cheers

**Comment by cmdoret** [comment]
Hi @aurelepiazza,

Yeah this is due to a change in the matplotlib api, upgrading matplotlib should do the trick :)

**Comment by aurelepiazza** [comment]
It did! Thanks :)
