### ISSUE TITLE
Missing File — abs_fragments_contacts_weighted

### ISSUE THREAD

**Issue by Overcraft90** [koszullab/hicstuff#62]
Hi I have a quick question,

I run **hicstuff** on a _A. thaliana_ genome using both HiFi long reads and HiC long rage data which I assembled with **HiFiasm**. I got both haplotypes and for now I'm focusing on hap1.

I used **minimap2** for both indexing and aligning the genome and the HiC reads sets, respectively. Later, I sorted the `.bam` files as indicated in the pipeline before running **hicstuff**. Nevertheless, for some reasons I'm missing the `abs_fragments_contacts_weighted.txt` file which is crucial for performing scaffolding with instaGRAAL.

Let me know whether I've done something wrong. 
Thanks in advance.

**Comment by ABignaud** [comment]
Hi,
It seems that hicstuff failed.
Could you send us the command line that you used and the hicstuff log's.

**Comment by Overcraft90** [comment]
Sure, following you can see the command I used:

`hicstuff pipeline -S bam -e 5000 -M cool -o out/ -g CRR302670.asm.hap1.fasta arabidopsis_thaliana_f1_sorted.bam arabidopsis_thaliana_r2_sorted.bam`, and

this is the `log file`
[hicstuff_20220404225407.log](https://github.com/koszullab/hicstuff/files/8416379/hicstuff_20220404225407.log)

I must say I got the data from a study, and even after checking I couldn't find any clue about what RE they used..., so I simply plugged in what you recommended.

**Comment by ABignaud** [comment]
The `-M cool` will give you a matrix in cool format as output which is not compatible with instaGRAAl. if you an `abs_fragments_contacts_weighted.cool`, you can convert it into a graal matrix using `hicstuff convert`.

But I think something went wrong before generating the matrix as you do not have the last line in the log "Contact map generated after ...". May be cooler was not install. (you can try `cooler -h` to check if it's installed.). If it's the case relaunch it without the `-M cool` option. Otherwise, od you have any error message in your terminal.

For the enzyme you can try 1000, most of the enzyme should have at least one restriction sites every kb.

**Comment by Overcraft90** [comment]
You are right it asks to install cooler with the command:

`sudo apt install python3-cooler`

can I proceed? Then, I will try again and let you know.

**Comment by ABignaud** [comment]
If you want to use instagraal after, you could not use cooler format. So you can just remove `-M cool` option without installing cooler. If you want a cooler matrix for some other analysis you can proceed and generate a cooler matrix. However you will need to convert the matrix in graal format for instagraal. It will be possible using `hicstuff convert` command.

**Comment by Overcraft90** [comment]
Sure I understand, I like to get the matrix anyway. To this extent the command I wrote, suggested by the shell, does something different from what the cooler Github page suggests? This is just for my information, sorry but I'm quite new to the field.

**Comment by ABignaud** [comment]
You should install it with `pip` or `conda` and not with `apt install `.

**Comment by Overcraft90** [comment]
Thanks, I will do it and let you know how it goes.

**Comment by Overcraft90** [comment]
Hi again,

Just done as you recommended me; unfortunately, for some reason (both using -M cooler and not using it) I still cannot get the `abs_fragments_contacts_weighted.txt`. The log file looks identical at every run as well, any idea?

However, based on the output on screen I can see it says: 

> INFO :: ## hicstuff: v3.1.2 log file
> INFO :: ## date: 2022-04-05 11:46:54
> INFO :: ## enzyme: 1000
> INFO :: ## input1: arabidopsis_thaliana_f1_sorted.bam 
> INFO :: ## input2: arabidopsis_thaliana_r2_sorted.bam
> INFO :: ## ref: CRR302670.asm.hap1.fasta
> INFO :: ---
> INFO :: Genome digested into 189565 fragments with a median length of 1000.0
> [E::idx_find_and_load] Could not retrieve index file for 'arabidopsis_thaliana_f1_sorted.bam'
> [E::idx_find_and_load] Could not retrieve index file for 'arabidopsis_thaliana_r2_sorted.bam'
> WARNING :: 23353870 reads were only present in one BAM file. Make sure you sorted reads by name before running the pipeline.
> INFO :: 70% reads (single ends) mapped with Q >= 30 (244373112/348948090)
> Traceback (most recent call last):
>   File "/home/mat/anaconda3/envs/quality_check/bin/hicstuff", line 8, in <module>
>     sys.exit(main())
>   File "/home/mat/anaconda3/envs/quality_check/lib/python3.9/site-packages/hicstuff/main.py", line 56, in main
>     command.execute()
>   File "/home/mat/anaconda3/envs/quality_check/lib/python3.9/site-packages/hicstuff/commands.py", line 865, in execute
>     hpi.full_pipeline(
>   File "/home/mat/anaconda3/envs/quality_check/lib/python3.9/site-packages/hicstuff/pipeline.py", line 854, in full_pipeline
>     hcd.attribute_fragments(pairs, pairs_idx, restrict_table)
>   File "/home/mat/anaconda3/envs/quality_check/lib/python3.9/site-packages/hicstuff/digest.py", line 234, in attribute_fragments
>     int(pair["pos2"]) - 1, restriction_table[pair["chr2"]]
> KeyError: 'h2tg000002l'

possibly referring to the indexing process not retrieved. That is strange because I've done that in **minimap2**...

**Comment by ABignaud** [comment]
Ok it seems that they are some weird names in your fasta as referring at the issue #61.
You can check the name of your fasta sequences and remove special character such as ' ', '|', ',', ':'

**Comment by Overcraft90** [comment]
Hi,

I actually checked the `fasta`, but I couldn't spot any of the issues you pointed out. I, then, talked with some of my colleagues to see whether they faced similar problems with other applications. At the end I found out the problem was I didn't index the `bam`.

So, I proceeded to do so with **samtools**; however, I was prompted with an error which even after checking didn't make any sense to me. I thought it could have been related to the fact I combined different tools, say I firstly used _minimap2_ for indexing the fasta and later switched to _samtools_. For this reason I tried to start over the whole procedure using **bwa+samtools**. Apparently was not this causing trouble; in fact, I got the same error message.

Finally thinking to step back a bit, although I had already the `bam`s, I decided to simply run the command:
> hicstuff pipeline -t 16 -a minimap2 -e 1000 -o out/ -g CRR302670.asm.hap1.fasta ../arabidopsis_thaliana/Hi-C/CRR302670_f1.fastq ../arabidopsis_thaliana/Hi-C/CRR302670_r2.fastq

which returned me with the correct files I need to feed to instaGRAAL. Sorry for all this, probably the solution was easier than expected, I just wanted to see if I could manage with the data I already generated without having to redo everything from the beginning.
