### ISSUE TITLE
Segmentation fault core dumped

### ISSUE THREAD

**Issue by ghost** [koszullab/hicstuff#86]
Hello, here is the issue I have encountered

```
hicstuff pipeline --enzyme "DpnII" --binning 1000 --duplicates --filter --distance-law --plot --threads 20 -a bwa --genome assembly.fa --force SRR13348925_1.fastq.gz SRR13348925_2.fastq.gz
INFO :: ## hicstuff: v3.2.4 log file
INFO :: ## date: 2024-09-18 15:21:47
INFO :: ## enzyme: DpnII
INFO :: ## input1: SRR13348925_1.fastq.gz 
INFO :: ## input2: SRR13348925_2.fastq.gz
INFO :: ## ref: assembly.fa
INFO :: ---
INFO :: The default output format is now `.cool`. The Hi-C matrix will be generated with cooler v0.10.2 (Abdennur & Mirny, Bioinformatics 2020).
INFO :: Checking content of fastq files.
INFO :: 55462178 reads found in each fastq file.
Segmentation fault (core dumped)
[main_samview] fail to read the header from "/media/alessandro/Storage/MA/September_2024_PacBio_HiFi/AV24_hifiasm/GraphUnzip/tmp/for.bam.tmp".
[W::hts_set_opt] Cannot change block size for this format
samtools sort: failed to read header from "-"
Segmentation fault (core dumped)
[main_samview] fail to read the header from "/media/alessandro/Storage/MA/September_2024_PacBio_HiFi/AV24_hifiasm/GraphUnzip/tmp/rev.bam.tmp".
[W::hts_set_opt] Cannot change block size for this format
samtools sort: failed to read header from "-"
Traceback (most recent call last):
  File "/home/alessandro/mambaforge/bin/hicstuff", line 33, in <module>
    sys.exit(load_entry_point('hicstuff', 'console_scripts', 'hicstuff')())
  File "/home/alessandro/software/src/hicstuff/hicstuff/main.py", line 57, in main
    command.execute()
  File "/home/alessandro/software/src/hicstuff/hicstuff/commands.py", line 891, in execute
    hpi.full_pipeline(
  File "/home/alessandro/software/src/hicstuff/hicstuff/pipeline.py", line 991, in full_pipeline
    bam2pairs(bam1, bam2, pairs, info_contigs, min_qual=min_qual)
  File "/home/alessandro/software/src/hicstuff/hicstuff/pipeline.py", line 146, in bam2pairs
    forward = ps.AlignmentFile(bam1, "rb")
  File "pysam/libcalignmentfile.pyx", line 747, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 952, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file does not contain alignment data

```

Any idea? bwa was installed by local compilation, and so far with bowtie2 it seems to work well, I will edit if it crashes at some point. I have no specific critical reason to have chosen bwa it's just the mapper I am used to use everywhere, just a "mapper habit". 

Thanks

**Comment by ghost** [comment]
Something  was wrong with the fasta file, no hicstuff issue, I am sorry, closing for now
